### ISSUE TITLE
firebase.js issues

### ISSUE THREAD

**Issue by hacktiger** [hacktiger/RNWeatherLocApp#10]
onStateChange runs onPress to chat
cant getUid() before chat ( or bf anything as a matter of fact )

**Comment by namnh240795** [comment]
như a đã nói là js nó sẽ chạy rất nhiều process trong 1 thread nên khi muốn nó chạy tuần tự thì phải dùng callback là 1, 2 là async await

**Comment by hacktiger** [comment]
fixed
